name: Release

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Docker
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.pkg.github.com
          sudo docker build -t docker.pkg.github.com/kate-social/frontend/react:latest .
          sudo docker push docker.pkg.github.com/kate-social/frontend/react:latest

      - name: Deploy
        uses: fjogeleit/http-request-action@master
        with:
          url: '${{ secrets.DEPLOY_HOST }}'
          method: 'POST'
          customHeaders: '{"token":"${{ secrets.DEPLOY_TOKEN }}"}'
          timeout: 60000
